const text = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`,
  `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
  `Lorem ipsum dolor sit amet, per nisl modo comprehensam ne, at nisl perpetua mei. Usu id ullum blandit, expetenda conclusionemque sea et. Fugit quidam inimicus eu vix, primis recteque ut quo. Ex idque aliquam vulputate sed, pri no omnium fierent mnesarchum `,
  `Ei mei vitae noluisse antiopam, enim delenit est no. Eos eu quando legendos, in zril inermis cum, per saperet persequeris ea. Eu vide ancillae appellantur has, augue salutandi suscipiantur et cum, vix postulant molestiae voluptatum ut. Id vim graece fuisset euripidis, id eos animal instructior, erat sadipscing contentiones vix et.`,
  `Te dicunt virtute fabellas nec, ut est elit consul equidem. An justo dissentiet efficiantur sea, ad nam quem alia incorrupte. An soleat nostro saperet sit. Inani simul duo ea. Dolorum singulis sed ex, diceret comprehensam sea at. Ad usu summo pertinax neglegentur. Ad vel habemus vulputate, wisi quando et nam.`,
  `Has et ubique maiestatis adolescens, at alia populo vix, elitr periculis per cu. Option copiosae reformidans cu vel, vis ex alterum vocibus. Cum natum percipit in. Qui utamur voluptatum efficiantur an, cum cu oporteat praesent, sit in dico omittam menandri.`,
  `Soleat principes concludaturque sea te, perfecto imperdiet in eos. Dico singulis duo ei, nam ei etiam eleifend. Sea cu brute homero probatus, nemore inciderint sea ne. Vis et nominati scribentur, affert scriptorem omittantur ut eam.`,
  `Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.`,
];
export default text;